=== nerevu/HTTPSanction/app/schemas/api-config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/nerevu/HTTPSanction/features/app/schemas/config.schema.json",
  "title": "API Config",
  "description": "An exposed API Configuration",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "description": "Unique identifier for the API",
      "type": "string",
      "uniqueItems": true,
      "pattern": "^[a-z]+(-[a-z]+)*$",
      "default": "",
      "examples": [
        "default",
        "awesome-api"
      ]
    },
    "description": {
      "description": "The API description",
      "type": "string",
      "default": "",
      "examples": [
        "Authenticates with various 3rd party services!"
      ]
    },
    "message": {
      "description": "Text to display on the API root route",
      "type": "string",
      "default": "",
      "examples": [
        "Welcome to the HTTPSanction!"
      ]
    },
    "methodViewRouteParams": {
      "description": "Exposed MethodView route params",
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "default": {},
        "$ref": "https://raw.githubusercontent.com/nerevu/HTTPSanction/features/app/schemas/method-view-route-params.schema.json"
      }
    },
    "blueprintRouteParams": {
      "description": "Exposed Blueprint route params",
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "default": {},
        "$ref": "https://raw.githubusercontent.com/nerevu/HTTPSanction/features/app/schemas/blueprint-route-params.schema.json"
      }
    },
    "authRouteParams": {
      "description": "Exposed Auth params per provider",
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "default": {},
        "$ref": "https://raw.githubusercontent.com/nerevu/HTTPSanction/features/app/schemas/auth-route-params.schema.json"
      }
    },
    "providerNames": {
      "description": "Exposed provider prefixes",
      "type": "array",
      "default": [],
      "items": {
        "type": "string",
        "pattern": "^[a-z]+(-[a-z]+)*$",
        "default": "",
        "examples": [
          "xero",
          "airtable",
          "cloze"
        ]
      }
    }
  },
  "required": [
    "name",
    "description",
    "message",
    "methodViewRouteParams",
    "blueprintRouteParams"
  ]
}

=== nerevu/HTTPSanction/app/api_configs/default.json
{
  "name": "default",
  "description": "Authenticates with various 3rd party services!",
  "message": "Welcome to the HTTPSanction!",
  "methodViewRouteParams": [
    {
      "name": "memoization",
      "module": "app.routes",
      "className": "Memoization",
      "params": [
        "string:path"
      ],
      "methods": [
        "GET",
        "DELETE"
      ]
    }
  ],
  "authRouteParams": [
    {
      "name": "callback",
      "module": "app.routes.auth",
      "className": "Callback"
    },
    {
      "name": "auth",
      "module": "app.routes.auth",
      "className": "Auth",
      "methods": ["GET", "PATCH"]
    }
  ],
  "blueprintRouteParams": [
    {
      "name": "ipsum",
      "module": "app.routes",
      "funcName": "ipsum"
    }
  ],
  "providerNames": [
    "airtable",
    "cloze",
    "github",
    "gusto",
    "keycdn",
    "mailgun",
    "postmark",
    "quickbooks",
    "timely",
    "xero"
  ]
}
